CREATE USER MONITOR IDENTIFIED BY MONITOR; 

GRANT CREATE SESSION TO MONITOR; 

GRANT SELECT ON v_$waitclassmetric TO MONITOR; 

GRANT SELECT ON v_$system_wait_class TO MONITOR; 

GRANT SELECT ON v_$sysmetric TO MONITOR; 

GRANT SELECT ON v_$parameter TO MONITOR; 

GRANT SELECT ON v_$parameter TO MONITOR; 