
CREATE USER MONITOR IDENTIFIED BY MONITOR_123;

GRANT CREATE SESSION TO MONITOR;
GRANT SELECT  ON V_$WAITCLASSMETRIC TO MONITOR;
GRANT SELECT  ON V_$SYSTEM_WAIT_CLASS TO MONITOR;
GRANT SELECT  ON V_$SYSMETRIC TO MONITOR;
GRANT SELECT  ON V_$PARAMETER TO MONITOR;
GRANT SELECT  ON V_$EVENTMETRIC TO MONITOR;
GRANT SELECT  ON V_$EVENT_NAME TO MONITOR;
GRANT SELECT  ON DBA_DATA_FILES  TO MONITOR;
GRANT SELECT  ON dba_free_space  TO MONITOR;

--AWR
GRANT SELECT ON SYS.DBA_HIST_SNAPSHOT TO MONITOR;
GRANT SELECT ON SYS.DBA_HIST_DATABASE_INSTANCE TO MONITOR;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPOSITORY TO MONITOR;